/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class Helloworld */

#ifndef _Included_Helloworld
#define _Included_Helloworld
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Helloworld
 * Method:    Hello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Helloworld_Hello
  (JNIEnv *, jobject);

/*
 * Class:     Helloworld
 * Method:    send
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_Helloworld_send
  (JNIEnv *, jobject, jstring);

/*
 * Class:     Helloworld
 * Method:    sum
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_Helloworld_sum
  (JNIEnv *, jobject, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
